name: "Deploy CodigoFacilito"

on: [push]
branches:
    - main
jobs:
    deploy-codigofacilito:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hacemos pull del código"
            - run: echo "Corremos migraciones"
            - run: echo "Generamos binario"
            - run: echo "Publicar versión"
       
